// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ArchLens.Report.Tests.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ConsultaDeRelatoriosFeature : object, Xunit.IClassFixture<ConsultaDeRelatoriosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Consulta de Relatórios", "  Como um usuário da plataforma ArchLens\n  Eu quero consultar os relatórios de an" +
                "álise de arquitetura\n  Para visualizar os resultados das análises realizadas", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ConsultaRelatorio.feature"
#line hidden
        
        public ConsultaDeRelatoriosFeature(ConsultaDeRelatoriosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar relatório por ID com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar relatório por ID com sucesso")]
        public async System.Threading.Tasks.Task ConsultarRelatorioPorIDComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar relatório por ID com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um relatório com ID \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.WhenAsync("eu consultar o relatório pelo ID \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter o relatório com ID \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar relatório por ID inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar relatório por ID inexistente")]
        public async System.Threading.Tasks.Task ConsultarRelatorioPorIDInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar relatório por ID inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("que não existe relatório com ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.WhenAsync("eu consultar o relatório pelo ID \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("a resposta deve ter status code 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar relatório por análise com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar relatório por análise com sucesso")]
        public async System.Threading.Tasks.Task ConsultarRelatorioPorAnaliseComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar relatório por análise com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 22
    await testRunner.AndAsync("que existe um relatório para a análise \"22222222-2222-2222-2222-222222222222\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 23
    await testRunner.WhenAsync("eu consultar o relatório pela análise \"22222222-2222-2222-2222-222222222222\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 25
    await testRunner.AndAsync("a resposta deve conter a análise \"22222222-2222-2222-2222-222222222222\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar relatório por análise inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar relatório por análise inexistente")]
        public async System.Threading.Tasks.Task ConsultarRelatorioPorAnaliseInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar relatório por análise inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 29
    await testRunner.AndAsync("que não existe relatório para a análise \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 30
    await testRunner.WhenAsync("eu consultar o relatório pela análise \"99999999-9999-9999-9999-999999999999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("a resposta deve ter status code 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar relatórios com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Listar relatórios com sucesso")]
        public async System.Threading.Tasks.Task ListarRelatoriosComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar relatórios com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 35
    await testRunner.AndAsync("que existem relatórios cadastrados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 36
    await testRunner.WhenAsync("eu listar os relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar relatório sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar relatório sem autenticação")]
        public async System.Threading.Tasks.Task ConsultarRelatorioSemAutenticacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar relatório sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("que eu não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 41
    await testRunner.AndAsync("que existe um relatório com ID \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 42
    await testRunner.WhenAsync("eu consultar o relatório pelo ID \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("a resposta deve ter status code 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar relatórios com paginação")]
        [Xunit.TraitAttribute("FeatureTitle", "Consulta de Relatórios")]
        [Xunit.TraitAttribute("Description", "Listar relatórios com paginação")]
        public async System.Threading.Tasks.Task ListarRelatoriosComPaginacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar relatórios com paginação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 47
    await testRunner.AndAsync("que existem relatórios cadastrados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 48
    await testRunner.WhenAsync("eu listar os relatórios com página 1 e tamanho 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 49
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ConsultaDeRelatoriosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ConsultaDeRelatoriosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
