// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ArchLens.Report.Tests.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MetricasAdministrativasDeRelatoriosFeature : object, Xunit.IClassFixture<MetricasAdministrativasDeRelatoriosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Métricas administrativas de Relatórios", "  Como um administrador da plataforma ArchLens\n  Eu quero consultar as métricas d" +
                "e relatórios\n  Para monitorar a qualidade das análises de arquitetura", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MetricasAdmin.feature"
#line hidden
        
        public MetricasAdministrativasDeRelatoriosFeature(MetricasAdministrativasDeRelatoriosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar métricas com role Admin")]
        [Xunit.TraitAttribute("FeatureTitle", "Métricas administrativas de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar métricas com role Admin")]
        public async System.Threading.Tasks.Task ConsultarMetricasComRoleAdmin()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar métricas com role Admin", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existem métricas de relatórios disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.WhenAsync("eu consultar as métricas administrativas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter as métricas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar métricas com role User")]
        [Xunit.TraitAttribute("FeatureTitle", "Métricas administrativas de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar métricas com role User")]
        public async System.Threading.Tasks.Task ConsultarMetricasComRoleUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar métricas com role User", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"User\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("que existem métricas de relatórios disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.WhenAsync("eu consultar as métricas administrativas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar métricas sem autenticação")]
        [Xunit.TraitAttribute("FeatureTitle", "Métricas administrativas de Relatórios")]
        [Xunit.TraitAttribute("Description", "Consultar métricas sem autenticação")]
        public async System.Threading.Tasks.Task ConsultarMetricasSemAutenticacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar métricas sem autenticação", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("que eu não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 22
    await testRunner.AndAsync("que existem métricas de relatórios disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 23
    await testRunner.WhenAsync("eu consultar as métricas administrativas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
    await testRunner.ThenAsync("a resposta deve ter status code 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Métricas retornam score médio correto")]
        [Xunit.TraitAttribute("FeatureTitle", "Métricas administrativas de Relatórios")]
        [Xunit.TraitAttribute("Description", "Métricas retornam score médio correto")]
        public async System.Threading.Tasks.Task MetricasRetornamScoreMedioCorreto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Métricas retornam score médio correto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.AndAsync("que existem métricas com score médio de 8.5", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 29
    await testRunner.WhenAsync("eu consultar as métricas administrativas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 30
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 31
    await testRunner.AndAsync("a resposta deve conter score médio de 8.5", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Métricas retornam uso de providers")]
        [Xunit.TraitAttribute("FeatureTitle", "Métricas administrativas de Relatórios")]
        [Xunit.TraitAttribute("Description", "Métricas retornam uso de providers")]
        public async System.Threading.Tasks.Task MetricasRetornamUsoDeProviders()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Métricas retornam uso de providers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("que eu sou um usuário autenticado com role \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 35
    await testRunner.AndAsync("que existem métricas de relatórios disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 36
    await testRunner.WhenAsync("eu consultar as métricas administrativas de relatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("a resposta deve ter status code 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("a resposta deve conter uso de providers", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MetricasAdministrativasDeRelatoriosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MetricasAdministrativasDeRelatoriosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
